### ISSUE TITLE
Too restrictive versioning in install_requires.txt 

### ISSUE THREAD

**Issue by jonmd** [AltSchool/dynamic-rest#118]
Nice project. I tried it right about now because of the DynamicRelationField.

When I added dynamic-rest to my project via `pip install dynamic-rest`, it downgraded Django to 1.9 and REST Framework to 3.3.0. The latest versions are 1.9.7 and 3.3.3 respectively. Django has had both bug- and vulnerability patches in 1.9 release, so it would be nice to get the latest patch. 

As I'm guessing this is because of these lines in install_requires.txt:

    Django>=1.7,<=1.9
    djangorestframework>=3.1.0,<=3.3.0

Could you for instance update this to:

    Django>=1.7,<1.10
    djangorestframework>=3.1.0,<3.4.0

Thanks.

**Comment by aleontiev** [comment]
@jonmd glad you like the project. We have those versions locked in because those are the versions that we're explicitly supporting/testing via tox. 

PRs are welcome; if you change the install_requires.txt file and the tox.ini file here: `https://github.com/AltSchool/dynamic-est/blob/master/tox.ini` to include the versions you want to support, then verify support with `make tox`, I will merge in expansion of these versions.

**Comment by aleontiev** [comment]
@jonmd we have just added compatibility testing and support for DRF 3.4 as well as Django 1.10, and have broadened the setup.py requirements accordingly; all DRF 3.3/Django 1.9 versions should be accepted.
