### ISSUE TITLE
Taggit Prefetching

### ISSUE THREAD

**Issue by johnhuffsmith** [AltSchool/dynamic-rest#163]
I'm using the Taggit library (https://github.com/alex/django-taggit) and have run into an issue when exposing `tags` on one of my serializers:

The field looks like this :
```
tags = DynamicRelationField(TagSerializers,
                many=True,
                read_only=True)
```

It blows up with this error from the taggit object manager: https://github.com/alex/django-taggit/blob/master/taggit/managers.py#L100

I've tried adding `requires=['tags.*', '*'],` but I get the same error.

1. Why does DREST set the prefect queryset?
2. Is there a way to not set the prefect queryset?

Thanks!

**Comment by aleontiev** [comment]
1. DREST supports efficient filterable sideloads by constructing a "prefetch tree" of querysets that guarantees only one query is executed per fetched model, rather than one query per object.

For example, lets say you have a "User" model with a "tags" many-relationship (ignoring taggit for a second), and you make the following request to get all users, along with a subset of their tags based on a filter:

```
GET /users/?include[]=tags.*&filter{tags|name.icontains}=foo
```

DREST translates this request to the following prefetch tree before passing it to the serializer layer:

```
User.objects.all().prefetch_related(
    Prefetch(
        'tags',
        queryset=Tag.objects.filter(
            name__icontains='foo'
        )
    )
)
```

Similarly, you can also define a default queryset on the `DynamicRelationField` to perform this filtering on every requests, e.g. if you always want to return a specific subset of a relationship.

2) ... but let's say you don't care about filtering sideloads, and you make this simpler request:

```
GET /users/?include[]=tags.*
```

DREST translates this to:

```
User.objects.all().prefetch_related(
    Prefetch(
        'tags',
        queryset=Tag.objects.all()
    )
)
```

Technically, the queryset passed to the "tags" prefetch is redundant in this case, but DREST still provides it for internal consistency.

There is no way to disable this -- I think your best bet is to patch `django-taggit` not to throw an error if the prefetch queryset has no actual filters on it.
