### ISSUE TITLE
one-to-many relations aren't deferred for PUT/PATCH

### ISSUE THREAD

**Issue by Incanus3** [AltSchool/dynamic-rest#262]
List of (one-to-many) related ids is returned for PUT/PATCH even though DynamicRelationField is deferred both in settings and in serializer definition. This is a big problem if you imagine e.g. a User having thousands of Transactions, then when you want to (partially) update User (e.g. change his/her name), you get back the complete list of his/her Transaction ids.

I've created a minimal project reproducing this issue [here](https://github.com/Incanus3/dynamic-rest-deferred-many-relations-test). You can see that the relation field is deffered both [in settings](https://github.com/Incanus3/dynamic-rest-deferred-many-relations-test/blob/master/related_ids_test/settings.py#L78) and [in serializer](https://github.com/Incanus3/dynamic-rest-deferred-many-relations-test/blob/master/related_ids_test/serializers.py#L14). When you create a Parent record with some Child records and then try to PATCH the Parent record, related Child ids are included in PATCH response. Should I try to investigate further or is this for some reason the desired behavior?

**Comment by Incanus3** [comment]
as a side note, the latest tag is v1.9.2, but the VERSION in setup.py is still 1.9.1

**Comment by Incanus3** [comment]
I just found out that [this line](https://github.com/AltSchool/dynamic-rest/blob/master/dynamic_rest/viewsets.py#L293) is causing the problem. Can someone explain, why this is needed here?

**Comment by ryochiji** [comment]
It's a bit out of laziness, tbh. On update requests, if a field that's deferred is updated, the update can fail because the field doesn't exist as far as some parts of the code are concerned (and I can't remember if the issue in DREST or DRF). Just including all fields by default on update requests was an easy solution. (What @DeviateFish describes above is sort of a secondary benefit.)

A better solution would be to actually detect which fields are being patched, and include those. I actually have a local branch that does just that, but haven't merged it because there are a couple of edge cases to think through (including the fact that this would change the shape of responses in update requests, and I'm not certain that won't cause problems).

**Comment by Incanus3** [comment]
OK, thanks for the explanation. This is actually not a big problem in my code, as I already have a custom subclass of `DynamicModelViewSet`, so I can just override the `get_serializer` method there, but I think this behavior can be quite surprising for other users and should be at least documented.
